CREATE TABLE ACMS_MST.T_USER
(
  ID        NUMBER,
  EMAIL     VARCHAR2(255 BYTE),
  USERNAME  VARCHAR2(255 BYTE)
);

CREATE SEQUENCE ACMS_MST.S_USER
START WITH 0
INCREMENT BY 1
MINVALUE 0
NOCACHE 
NOCYCLE 
NOORDER;